title: Rakesh Panigrahy
logo: /assets/img/passphoto.jpg
# logo: https://www.linkedin.com/in/rakesh-panigrahy-062166102/?lipi=urn%3Ali%3Apage%3Ad_flagship3_feed%3BiFyQL0yNRu%2BQrIo%2FDsHueA%3D%3D
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
